# Generated by Django 6.0.2 on 2026-02-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radboox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('nas', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Aktif', max_length=20)),
            ],
            options={
                'verbose_name': 'Data Radboox',
                'verbose_name_plural': 'Data Radboox',
            },
        ),
        migrations.CreateModel(
            name='Gangguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_wa', models.CharField(max_length=20)),
                ('keluhan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Progress', 'Progress'), ('Done', 'Done')], default='Open', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_radius', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('invoice_status', models.CharField(max_length=20)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_wa', models.CharField(max_length=20)),
                ('bulan_tagihan', models.CharField(max_length=50)),
                ('bukti_transfer', models.ImageField(upload_to='bukti/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
