# Generated by Django 6.0.2 on 2026-02-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radboox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=100, null=True)),
                ('nas', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='No Telepon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Import')),
                ('status', models.CharField(default='Aktif', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Data Radboox',
                'verbose_name_plural': 'Data Radboox',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Gangguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Laporan')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Gangguan')),
                ('kategori', models.CharField(choices=[('jaringan', 'Jaringan'), ('perangkat', 'Perangkat'), ('tagihan', 'Tagihan'), ('lainnya', 'Lainnya')], default='jaringan', max_length=50, verbose_name='Kategori')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Laporan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('proses', 'Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gangguan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gangguan',
                'verbose_name_plural': 'Gangguan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('no_wa', models.CharField(max_length=20, verbose_name='Nomor WhatsApp')),
                ('bulan_tagihan', models.CharField(max_length=20, verbose_name='Bulan Tagihan')),
                ('bukti_transfer', models.FileField(upload_to='bukti_bayar/', verbose_name='Bukti Transfer')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-tanggal'],
            },
        ),
    ]
