# Generated by Django 6.0.2 on 2026-02-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_gangguan_user_pembayaran_user_alter_gangguan_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_radius', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('invoice_status', models.CharField(max_length=20)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
